package com.example.sgr.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.sgr.green.dbBean.Student;
import com.example.sgr.green.dbBean.Users;
import com.example.sgr.green.dbBean.Test;

import com.example.sgr.greendao.StudentDao;
import com.example.sgr.greendao.UsersDao;
import com.example.sgr.greendao.TestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig usersDaoConfig;
    private final DaoConfig testDaoConfig;

    private final StudentDao studentDao;
    private final UsersDao usersDao;
    private final TestDao testDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        testDaoConfig = daoConfigMap.get(TestDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);
        testDao = new TestDao(testDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(Users.class, usersDao);
        registerDao(Test.class, testDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        usersDaoConfig.clearIdentityScope();
        testDaoConfig.clearIdentityScope();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public TestDao getTestDao() {
        return testDao;
    }

}
